package com.saurabhsandav.trading.record.stats

import com.saurabhsandav.trading.core.Instrument
import com.saurabhsandav.trading.core.SymbolId
import com.saurabhsandav.trading.record.Trade
import com.saurabhsandav.trading.record.model.TradeId
import com.saurabhsandav.trading.record.model.TradeSide
import com.saurabhsandav.trading.test.TestBroker
import java.math.BigDecimal
import kotlin.time.Instant

object TradingStatsUtils {

    val trades = listOf(
        Trade(
            id = TradeId(331),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "80".toBigDecimal(),
            closedQuantity = "80".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "475".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706175692),
            averageExit = "472.5".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706175990),
            pnl = "200".toBigDecimal(),
            fees = "14.19".toBigDecimal(),
            netPnl = "185.81".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(332),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("NTPC"),
            instrument = Instrument.Equity,
            quantity = "114".toBigDecimal(),
            closedQuantity = "114".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "320.7".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706503676),
            averageExit = "319.2".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706504572),
            pnl = "-171".toBigDecimal(),
            fees = "13.06".toBigDecimal(),
            netPnl = "-184.06".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(333),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("NTPC"),
            instrument = Instrument.Equity,
            quantity = "114".toBigDecimal(),
            closedQuantity = "114".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "319.2".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706504572),
            averageExit = "320.7".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706506067),
            pnl = "-171".toBigDecimal(),
            fees = "13.06".toBigDecimal(),
            netPnl = "-184.06".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(334),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toBigDecimal(),
            closedQuantity = "105".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "401".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706507742),
            averageExit = "402.65".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706508933),
            pnl = "-173.25".toBigDecimal(),
            fees = "15.53".toBigDecimal(),
            netPnl = "-188.78".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(335),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toBigDecimal(),
            closedQuantity = "105".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "402.5".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706508972),
            averageExit = "405.5".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706514900),
            pnl = "315".toBigDecimal(),
            fees = "15.55".toBigDecimal(),
            netPnl = "299.45".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(336),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toBigDecimal(),
            closedQuantity = "105".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "406".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706515797),
            averageExit = "406.2".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706515945),
            pnl = "21".toBigDecimal(),
            fees = "15.58".toBigDecimal(),
            netPnl = "5.42".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(337),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "86".toBigDecimal(),
            closedQuantity = "86".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "494".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706516947),
            averageExit = "498.5".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706517625),
            pnl = "387".toBigDecimal(),
            fees = "15.58".toBigDecimal(),
            netPnl = "371.42".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(338),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "106".toBigDecimal(),
            closedQuantity = "106".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "410.25".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706589353),
            averageExit = "408".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706592098),
            pnl = "-238.5".toBigDecimal(),
            fees = "15.63".toBigDecimal(),
            netPnl = "-254.13".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(339),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toBigDecimal(),
            closedQuantity = "140".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "262".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706592682),
            averageExit = "260".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706594062),
            pnl = "-280".toBigDecimal(),
            fees = "13.06".toBigDecimal(),
            netPnl = "-293.06".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(340),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toBigDecimal(),
            closedQuantity = "140".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "260.05".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706594122),
            averageExit = "262".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706595099),
            pnl = "-273".toBigDecimal(),
            fees = "13.06".toBigDecimal(),
            netPnl = "-286.06".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(341),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toBigDecimal(),
            closedQuantity = "140".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "261.5".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706595169),
            averageExit = "259.5".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706596651),
            pnl = "-280".toBigDecimal(),
            fees = "13.06".toBigDecimal(),
            netPnl = "-293.06".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(342),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toBigDecimal(),
            closedQuantity = "140".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "259.5".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706596651),
            averageExit = "251.7".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706605806),
            pnl = "1092".toBigDecimal(),
            fees = "13".toBigDecimal(),
            netPnl = "1079".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(343),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "86".toBigDecimal(),
            closedQuantity = "86".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "507".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706606179),
            averageExit = "506".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706607225),
            pnl = "86".toBigDecimal(),
            fees = "15.66".toBigDecimal(),
            netPnl = "70.34".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(344),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "113".toBigDecimal(),
            closedQuantity = "113".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "248".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706680896),
            averageExit = "249.5".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706681327),
            pnl = "-169.5".toBigDecimal(),
            fees = "10.36".toBigDecimal(),
            netPnl = "-179.86".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(345),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("POWERGRID"),
            instrument = Instrument.Equity,
            quantity = "170".toBigDecimal(),
            closedQuantity = "170".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "257".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706681483),
            averageExit = "255.95".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706681906),
            pnl = "-178.5".toBigDecimal(),
            fees = "15.66".toBigDecimal(),
            netPnl = "-194.16".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(346),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "113".toBigDecimal(),
            closedQuantity = "113".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "250.95".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706681933),
            averageExit = "249.45".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706683240),
            pnl = "-169.5".toBigDecimal(),
            fees = "10.37".toBigDecimal(),
            netPnl = "-179.87".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(347),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toBigDecimal(),
            closedQuantity = "120".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "249.5".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706683306),
            averageExit = "251.05".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706684257),
            pnl = "-186".toBigDecimal(),
            fees = "10.51".toBigDecimal(),
            netPnl = "-196.51".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(348),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toBigDecimal(),
            closedQuantity = "120".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "251".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706684278),
            averageExit = "249.45".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706685931),
            pnl = "-186".toBigDecimal(),
            fees = "10.51".toBigDecimal(),
            netPnl = "-196.51".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(349),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toBigDecimal(),
            closedQuantity = "120".toBigDecimal(),
            lots = null,
            side = TradeSide.Short,
            averageEntry = "249".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706686287),
            averageExit = "250.55".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706691303),
            pnl = "-186".toBigDecimal(),
            fees = "10.51".toBigDecimal(),
            netPnl = "-196.51".toBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(350),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("POWERGRID"),
            instrument = Instrument.Equity,
            quantity = "140".toBigDecimal(),
            closedQuantity = "140".toBigDecimal(),
            lots = null,
            side = TradeSide.Long,
            averageEntry = "267.75".toBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706764086),
            averageExit = "266.7".toBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706766397),
            pnl = "-147".toBigDecimal(),
            fees = "13.13".toBigDecimal(),
            netPnl = "-160.13".toBigDecimal(),
            isClosed = true,
        ),
    )

    val winTrades = trades.filter { it.pnl > BigDecimal.ZERO }

    val lossTrades = trades.filter { it.pnl < BigDecimal.ZERO }

    /*
        // To get trades from saved TradingRecords

        private fun Trade.pretty(): String = buildString {
            append("Trade(")
            append("id = TradeId($id), ")
            append("brokerId = TestBroker.Id, ")
            append("symbol = Symbol(\"$symbol\", ")
            append("instrument = Instrument.Equity, ")
            append("quantity = \"$quantity\".toBigDecimal(), ")
            append("closedQuantity = \"$closedQuantity\".toBigDecimal(), ")
            append("lots = null, ")
            append("side = TradeSide.$side, ")
            append("averageEntry = \"$averageEntry\".toBigDecimal(), ")
            append("entryTimestamp = Instant.fromEpochSeconds(${entryTimestamp.epochSeconds}), ")
            append("averageExit = \"$averageExit\".toBigDecimal(), ")
            append("exitTimestamp = Instant.fromEpochSeconds(${exitTimestamp!!.epochSeconds}), ")
            append("pnl=\"$pnl\".toBigDecimal(), ")
            append("fees=\"$fees\".toBigDecimal(), ")
            append("netPnl=\"$netPnl\".toBigDecimal(), ")
            append("isClosed=$isClosed")
            append("),")
        }
     */
}
