package com.saurabhsandav.trading.record.stats

import com.saurabhsandav.kbigdecimal.KBigDecimal
import com.saurabhsandav.kbigdecimal.toKBigDecimal
import com.saurabhsandav.trading.core.Instrument
import com.saurabhsandav.trading.core.SymbolId
import com.saurabhsandav.trading.record.Trade
import com.saurabhsandav.trading.record.model.TradeId
import com.saurabhsandav.trading.record.model.TradeSide
import com.saurabhsandav.trading.test.TestBroker
import kotlin.time.Instant

object TradingStatsUtils {

    val trades = listOf(
        Trade(
            id = TradeId(331),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "80".toKBigDecimal(),
            closedQuantity = "80".toKBigDecimal(),
            lots = 80,
            closedLots = 80,
            side = TradeSide.Short,
            averageEntry = "475".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706175692),
            averageExit = "472.5".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706175990),
            pnl = "200".toKBigDecimal(),
            fees = "14.19".toKBigDecimal(),
            netPnl = "185.81".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(332),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("NTPC"),
            instrument = Instrument.Equity,
            quantity = "114".toKBigDecimal(),
            closedQuantity = "114".toKBigDecimal(),
            lots = 114,
            closedLots = 114,
            side = TradeSide.Long,
            averageEntry = "320.7".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706503676),
            averageExit = "319.2".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706504572),
            pnl = "-171".toKBigDecimal(),
            fees = "13.06".toKBigDecimal(),
            netPnl = "-184.06".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(333),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("NTPC"),
            instrument = Instrument.Equity,
            quantity = "114".toKBigDecimal(),
            closedQuantity = "114".toKBigDecimal(),
            lots = 114,
            closedLots = 114,
            side = TradeSide.Short,
            averageEntry = "319.2".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706504572),
            averageExit = "320.7".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706506067),
            pnl = "-171".toKBigDecimal(),
            fees = "13.06".toKBigDecimal(),
            netPnl = "-184.06".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(334),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toKBigDecimal(),
            closedQuantity = "105".toKBigDecimal(),
            lots = 105,
            closedLots = 105,
            side = TradeSide.Short,
            averageEntry = "401".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706507742),
            averageExit = "402.65".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706508933),
            pnl = "-173.25".toKBigDecimal(),
            fees = "15.53".toKBigDecimal(),
            netPnl = "-188.78".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(335),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toKBigDecimal(),
            closedQuantity = "105".toKBigDecimal(),
            lots = 105,
            closedLots = 105,
            side = TradeSide.Long,
            averageEntry = "402.5".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706508972),
            averageExit = "405.5".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706514900),
            pnl = "315".toKBigDecimal(),
            fees = "15.55".toKBigDecimal(),
            netPnl = "299.45".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(336),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "105".toKBigDecimal(),
            closedQuantity = "105".toKBigDecimal(),
            lots = 105,
            closedLots = 105,
            side = TradeSide.Long,
            averageEntry = "406".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706515797),
            averageExit = "406.2".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706515945),
            pnl = "21".toKBigDecimal(),
            fees = "15.58".toKBigDecimal(),
            netPnl = "5.42".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(337),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "86".toKBigDecimal(),
            closedQuantity = "86".toKBigDecimal(),
            lots = 86,
            closedLots = 86,
            side = TradeSide.Long,
            averageEntry = "494".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706516947),
            averageExit = "498.5".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706517625),
            pnl = "387".toKBigDecimal(),
            fees = "15.58".toKBigDecimal(),
            netPnl = "371.42".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(338),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("COALINDIA"),
            instrument = Instrument.Equity,
            quantity = "106".toKBigDecimal(),
            closedQuantity = "106".toKBigDecimal(),
            lots = 106,
            closedLots = 106,
            side = TradeSide.Long,
            averageEntry = "410.25".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706589353),
            averageExit = "408".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706592098),
            pnl = "-238.5".toKBigDecimal(),
            fees = "15.63".toKBigDecimal(),
            netPnl = "-254.13".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(339),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toKBigDecimal(),
            closedQuantity = "140".toKBigDecimal(),
            lots = 140,
            closedLots = 140,
            side = TradeSide.Long,
            averageEntry = "262".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706592682),
            averageExit = "260".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706594062),
            pnl = "-280".toKBigDecimal(),
            fees = "13.06".toKBigDecimal(),
            netPnl = "-293.06".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(340),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toKBigDecimal(),
            closedQuantity = "140".toKBigDecimal(),
            lots = 140,
            closedLots = 140,
            side = TradeSide.Short,
            averageEntry = "260.05".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706594122),
            averageExit = "262".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706595099),
            pnl = "-273".toKBigDecimal(),
            fees = "13.06".toKBigDecimal(),
            netPnl = "-286.06".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(341),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toKBigDecimal(),
            closedQuantity = "140".toKBigDecimal(),
            lots = 140,
            closedLots = 140,
            side = TradeSide.Long,
            averageEntry = "261.5".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706595169),
            averageExit = "259.5".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706596651),
            pnl = "-280".toKBigDecimal(),
            fees = "13.06".toKBigDecimal(),
            netPnl = "-293.06".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(342),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "140".toKBigDecimal(),
            closedQuantity = "140".toKBigDecimal(),
            lots = 140,
            closedLots = 140,
            side = TradeSide.Short,
            averageEntry = "259.5".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706596651),
            averageExit = "251.7".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706605806),
            pnl = "1092".toKBigDecimal(),
            fees = "13".toKBigDecimal(),
            netPnl = "1079".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(343),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("BPCL"),
            instrument = Instrument.Equity,
            quantity = "86".toKBigDecimal(),
            closedQuantity = "86".toKBigDecimal(),
            lots = 86,
            closedLots = 86,
            side = TradeSide.Short,
            averageEntry = "507".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706606179),
            averageExit = "506".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706607225),
            pnl = "86".toKBigDecimal(),
            fees = "15.66".toKBigDecimal(),
            netPnl = "70.34".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(344),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "113".toKBigDecimal(),
            closedQuantity = "113".toKBigDecimal(),
            lots = 113,
            closedLots = 113,
            side = TradeSide.Short,
            averageEntry = "248".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706680896),
            averageExit = "249.5".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706681327),
            pnl = "-169.5".toKBigDecimal(),
            fees = "10.36".toKBigDecimal(),
            netPnl = "-179.86".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(345),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("POWERGRID"),
            instrument = Instrument.Equity,
            quantity = "170".toKBigDecimal(),
            closedQuantity = "170".toKBigDecimal(),
            lots = 170,
            closedLots = 170,
            side = TradeSide.Long,
            averageEntry = "257".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706681483),
            averageExit = "255.95".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706681906),
            pnl = "-178.5".toKBigDecimal(),
            fees = "15.66".toKBigDecimal(),
            netPnl = "-194.16".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(346),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "113".toKBigDecimal(),
            closedQuantity = "113".toKBigDecimal(),
            lots = 113,
            closedLots = 113,
            side = TradeSide.Long,
            averageEntry = "250.95".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706681933),
            averageExit = "249.45".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706683240),
            pnl = "-169.5".toKBigDecimal(),
            fees = "10.37".toKBigDecimal(),
            netPnl = "-179.87".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(347),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toKBigDecimal(),
            closedQuantity = "120".toKBigDecimal(),
            lots = 120,
            closedLots = 120,
            side = TradeSide.Short,
            averageEntry = "249.5".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706683306),
            averageExit = "251.05".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706684257),
            pnl = "-186".toKBigDecimal(),
            fees = "10.51".toKBigDecimal(),
            netPnl = "-196.51".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(348),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toKBigDecimal(),
            closedQuantity = "120".toKBigDecimal(),
            lots = 120,
            closedLots = 120,
            side = TradeSide.Long,
            averageEntry = "251".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706684278),
            averageExit = "249.45".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706685931),
            pnl = "-186".toKBigDecimal(),
            fees = "10.51".toKBigDecimal(),
            netPnl = "-196.51".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(349),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("ONGC"),
            instrument = Instrument.Equity,
            quantity = "120".toKBigDecimal(),
            closedQuantity = "120".toKBigDecimal(),
            lots = 120,
            closedLots = 120,
            side = TradeSide.Short,
            averageEntry = "249".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706686287),
            averageExit = "250.55".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706691303),
            pnl = "-186".toKBigDecimal(),
            fees = "10.51".toKBigDecimal(),
            netPnl = "-196.51".toKBigDecimal(),
            isClosed = true,
        ),
        Trade(
            id = TradeId(350),
            brokerId = TestBroker.Id,
            symbolId = SymbolId("POWERGRID"),
            instrument = Instrument.Equity,
            quantity = "140".toKBigDecimal(),
            closedQuantity = "140".toKBigDecimal(),
            lots = 140,
            closedLots = 140,
            side = TradeSide.Long,
            averageEntry = "267.75".toKBigDecimal(),
            entryTimestamp = Instant.fromEpochSeconds(1706764086),
            averageExit = "266.7".toKBigDecimal(),
            exitTimestamp = Instant.fromEpochSeconds(1706766397),
            pnl = "-147".toKBigDecimal(),
            fees = "13.13".toKBigDecimal(),
            netPnl = "-160.13".toKBigDecimal(),
            isClosed = true,
        ),
    )

    val winTrades = trades.filter { it.pnl > KBigDecimal.Zero }

    val lossTrades = trades.filter { it.pnl < KBigDecimal.Zero }

    /*
        // To get trades from saved TradingRecords

        private fun Trade.pretty(): String = buildString {
            append("Trade(")
            append("id = TradeId($id), ")
            append("brokerId = TestBroker.Id, ")
            append("symbol = Symbol(\"$symbol\", ")
            append("instrument = Instrument.Equity, ")
            append("quantity = \"$quantity\".toKBigDecimal(), ")
            append("closedQuantity = \"$closedQuantity\".toKBigDecimal(), ")
            append("lots = null, ")
            append("side = TradeSide.$side, ")
            append("averageEntry = \"$averageEntry\".toKBigDecimal(), ")
            append("entryTimestamp = Instant.fromEpochSeconds(${entryTimestamp.epochSeconds}), ")
            append("averageExit = \"$averageExit\".toKBigDecimal(), ")
            append("exitTimestamp = Instant.fromEpochSeconds(${exitTimestamp!!.epochSeconds}), ")
            append("pnl=\"$pnl\".toKBigDecimal(), ")
            append("fees=\"$fees\".toKBigDecimal(), ")
            append("netPnl=\"$netPnl\".toKBigDecimal(), ")
            append("isClosed=$isClosed")
            append("),")
        }
     */
}
